Quiz/QuestionThree/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using QuestionThree.DbContext;
using QuestionThree.Dtos;
using QuestionThree.Models;

namespace QuestionThree.Controllers
{
    public class ActorsController : BaseController
    {
        private readonly ILogger<ActorsController> _logger;

        private People people;
        private Result result;

        public ActorsController(IHttpClientFactory clientFactory, ILogger<ActorsController> logger, IMDbContext dbContext)
            : base(clientFactory, dbContext)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var persons = new List<PeopleExtended>();
            // fetch the swapi actors ...
            try
            {
                var request = GetRequest("people/");

                var response = await client.SendAsync(request);

                if (!response.IsSuccessStatusCode) return View(persons);

                var responseStream = await response.Content.ReadAsStringAsync();
                people = JsonConvert.DeserializeObject<People>(responseStream);

                foreach (var actorResult in people.Results)
                {
                    // get the id of the actor ..
                    var url = actorResult.Url.ToString();
                    var split = url.Split('/');
                    var actorId = split[split.Length - 2];
                    int.TryParse(actorId, out var intActorId);

                    // check if entry exists in the db ...
                    var dbEntry = await _dbContext.Actors.FirstOrDefaultAsync(f => f.PeopleId == intActorId);

                    var peopleExtended = new PeopleExtended
                    {
                        BirthYear = actorResult.BirthYear,
                        Created = actorResult.Created,
                        Edited = actorResult.Edited,
                        EyeColor = actorResult.EyeColor,
                        Films = actorResult.Films,
                        Gender = actorResult.Gender,
                        HairColor = actorResult.HairColor,
                        Height = actorResult.Height,
                        Homeworld = actorResult.Homeworld,
                        Name = actorResult.Name,
                        Mass = actorResult.Mass,
                        SkinColor = actorResult.SkinColor
                    };
                    if (dbEntry != null)
                        peopleExtended.IsFavorite = dbEntry.IsFavorite;

                    persons.Add(peopleExtended);
                }

                return View(persons);
            }
            catch (Exception e)
            {
                _logger.LogError($"Error fetching actors: {e.Message}");
                return View(persons);
            }
        }


        private async Task<Result> GetSwapiActor(int id)
        {
            try
            {
                var request = GetRequest($"people/{id}/");

                var response = await client.SendAsync(request);

                if (!response.IsSuccessStatusCode) return null;

                var responseStream = await response.Content.ReadAsStringAsync();
                var actorsResult = JsonConvert.DeserializeObject<Result>(responseStream);
                return actorsResult;
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var actor = await _dbContext.Actors.FirstOrDefaultAsync(w => w.PeopleId == id) ?? new Actor();
                actor.PeopleId = id;
                ViewData["result"] = await GetSwapiActor(id);

                return View(actor);
            }
            catch (Exception e)
            {
                _logger.LogError($"Error fetching actors: {e.Message}");
                return View();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Details([Bind("Id,PeopleId,IsFavorite")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                ViewData["result"] = await GetSwapiActor(actor.PeopleId);
                return View(actor);
            }


            // check if the entry exists in the db ...
            // if exists, update, else insert ..
            var dbEntry = await _dbContext.Actors.AsNoTracking().FirstOrDefaultAsync(w => w.PeopleId == actor.PeopleId);

            // get the number of favorites selected ...
            var favoritesCount = await _dbContext.Actors.AsNoTracking().Where(w => w.IsFavorite).CountAsync();

            if (dbEntry is null)
            {
                if (favoritesCount > 4)
                {
                    // show a message that, all favorites selection have been exhausted..
                    ViewData["showError"] = true;
                    ViewData["result"] = await GetSwapiActor(actor.PeopleId);
                    return View(actor);
                }
                _dbContext.Add(actor);
            }
            else
            {
                _dbContext.Update(actor);
            }

            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

Quiz/QuestionThree/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWAPI API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SWAPI API</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Actors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SWAPI API
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>